apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employees
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 32555
  type: NodePort