apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 2
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: sandhyasrini/employees:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
